<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [1]:
import numpy as np

In [11]:
np.random.seed(42)

# Input data
X = np.array([
    [0, 0, 1],
    [0, 1, 1],
    [1, 0, 1],
    [0, 1, 0],
    [1, 0, 1],
    [1, 1, 1],
    [0, 0, 0]
])

# True outputs
y = np.array([
    [0],
    [1],
    [1],
    [1],
    [1],
    [0],
    [0]
])

In [20]:
# build a neural network class
class NeuralNetwork:
    
    def __init__(self):
        self.inputs = 3
        self.hiddenNodes = 4
        self.outputNodes = 1
        
        # Initialize weights for input/hidden
        self.weights1 = np.random.randn(self.inputs, self.hiddenNodes)
        
        # Initialize weights for hidden/output
        self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)

In [13]:
nn = NeuralNetwork()

print('Layer 1 weights: \n', nn.weights1)
print('\nLayer 2 weights: \n', nn.weights2)

Layer 1 weights: 
 [[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]]

Layer 2 weights: 
 [[ 0.24196227]
 [-1.91328024]
 [-1.72491783]
 [-0.56228753]]


In [21]:
# Feedforward functionality
class NN(NeuralNetwork):

    # Implement activation function
    # Sigmoid curves go with binary values
    def sigmoid(self, s):
        return 1 / (1 + np.exp(-s))
    
    def feed_forward(self, X):
        
        # Weight Sum
        self.hidden_sum = np.dot(X, self.weights1)
        
        # Activation
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weighted Sum 2
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        # Final Output
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output

In [22]:
X[0]

array([0, 0, 1])

In [23]:
# Predict
nn = NN()
output = nn.feed_forward(X[0])
print('input', X[0])
print('output', output)
print('true_output', y[0])

input [0 0 1]
output [0.64084595]
true_output [0]


In [24]:
# Error
error = y[0] - output
print(error)

[-0.64084595]


In [25]:
output_all = nn.feed_forward(X)
error_all = y - output_all
print(output_all)
print(error_all)
print(y)

[[0.64084595]
 [0.44059085]
 [0.53392894]
 [0.3614157 ]
 [0.53392894]
 [0.40767823]
 [0.54466055]]
[[-0.64084595]
 [ 0.55940915]
 [ 0.46607106]
 [ 0.6385843 ]
 [ 0.46607106]
 [-0.40767823]
 [-0.54466055]]
[[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]


In [29]:
class NeuralNetwork:
    
    def __init__(self):
        self.inputs = 3
        self.hiddenNodes = 4
        self.outputNodes = 1
        self.weights1 = np.random.randn(self.inputs, self.hiddenNodes)
        self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)
        
    def sigmoid(self, s):
        return 1 / (1 + np.exp(-s))
    
    # Still not sure how the derivative of Sigmoid Curve comes into play
    def sigmoidPrime(self, s):
        sx = self.sigmoid(s)
        return sx * (1 - sx)
    
    # NN interference
    def feed_forward(self, X):
        self.hidden_sum = np.dot(X, self.weights1)
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        self.activated_output = self.sigmoid(self.output_sum)
        return self.activated_output
    
    # Backpropagation
    def backward(self, X,y,o):
        self.o_error = y - o
        self.o_delta = self.o_error * self.sigmoidPrime(self.output_sum)
        self.z2_error = self.o_delta.dot(self.weights2.T)
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.hidden_sum)
        self.weights1 += X.T.dot(self.z2_delta) #Adjust first set (input => hidden) weights
        self.weights2 += self.activated_hidden.T.dot(self.o_delta) #adjust second set (hidden => output) weights
        
    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X,y,o)

In [36]:
# Train NN through many epochs
nn = NeuralNetwork()

for i in range(10000):
    if (i + 1 in [1, 2, 3, 4, 5]) or ((i + 1) % 1000 == 0):
        print(f'---------EPOCH {i + 1} ---------')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print('Loss: \n', str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X, y)

---------EPOCH 1 ---------
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 1]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.15039214]
 [0.14833608]
 [0.15776758]
 [0.18680186]
 [0.15776758]
 [0.15694548]
 [0.19113235]]
Loss: 
 0.4127306861381211
---------EPOCH 2 ---------
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 1]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.2346431 ]
 [0.24035442]
 [0.26519036]
 [0.27564127]
 [0.26519036]
 [0.26805119]
 [0.26888607]]
Loss: 
 0.34012227772792897
---------EPOCH 3 ---------
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 1]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.35200485]
 [0.36973366]
 [0.41503618]
 [0.39251964]
 [0.41503618]
 [0.42248396]
 [0.37176531]]
Loss: 
 0.2701775619027809
---------EPOCH 4 ---------
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 1]
 [1 1 1]
 [0 0 0]]
Ac

In [ ]:
# Values trend toward predicted outputs at the 1000 epoch mark and taper off after 4000 iterations

## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


In [ ]:
##### Your Code Here #####

## Stretch Goals: 

- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?